import math

a = math.err_func(1)
